### ISSUE TITLE
No resource or method named `docker?' for `Custom resource swap_file from cookbook swap action provider "/tmp/swap"'

### ISSUE THREAD

**Issue by patrickviet** [sous-chefs/swap#52]
### Cookbook version
2.0.0 (commit 49255d895aa85e29ad43bc3eeacecb783f047bf3)

### Chef-client version
12.10.24

### Platform Details
Centos 6.9

### Scenario:
```swap_file '/tmp/swap' do
  size 1024
end
```

### Steps to Reproduce:
Have a chef setup that doesn't have the docker 'extension' or whatnot?

### Expected Result:
Create a swap file and swap on it.

### Actual Result:
```
    NoMethodError
    -------------
    No resource or method named `docker?' for `Custom resource swap_file from cookbook swap action provider "/tmp/swap"'

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/swap/resources/file.rb:108:in `swap_creation_command'
    /var/chef/cache/cookbooks/swap/resources/file.rb:30:in `block in class_from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/st-base/recipes/swap.rb

      1: swap_file '/tmp/swap' do
      2:   size 1024
      3:   persist true
      4:   action :remove unless node['memory']['swap']['total'] == '0kB'
      5: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/st-base/recipes/swap.rb:1:in `from_file'

    swap_file("/tmp/swap") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :swap_file
      cookbook_name "st-base"
      recipe_name "swap"
      size 1024
      persist true
      path "/tmp/swap"
    end

    Platform:
    ---------
    x86_64-linux
```

**Comment by patrickviet** [comment]
was able to temporarily resolve it by taking out the '&& docker?' part from resource/file.rb

**Comment by tas50** [comment]
Yep looks like we accidentally used a Chef 13-ism. If you upgrade to 13+ this goes away, but we should fix it for Chef 12 users and get testing on older chef releases as well.

**Comment by tas50** [comment]
This is fixed in the latest release. Give it a try
